[tool.poetry]
name = "x12-utils"
version = "0.1.0"
description = ""
authors = ["willingham <thomas@tshows.us>"]

[tool.poetry.dependencies]
python = "^3.7"
pyx12 = "^2.3"
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[tool.poetry.dev-dependencies]
pytest = "^3.0"
mypy = "^0.701.0"
pytest-cov = "^2.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
