[tool.poetry]
name = "x12-validator"
version = "0.1.0"
description = ""
authors = ["willingham <thomas@tshows.us>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
